Repository DeveloperAcademy-POSTECH/MC3-Team8-FOX, pull requests merged in 2022-08, with the labels that each got.

#65 [Feat] MeetSchedule의 하이파이수정
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/Supports/UIColor+Extension.swift
  MC3_Team8_FOX/Source/Supports/UIView+Extension.swift
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleTableViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/ScheduleCell.swift
Labels: @Livvy

#61 [Feat] connecting view hi-fi 맞춰 레이아웃 만들기
  MC3_Team8_FOX/Resource/Storyboard/Connecting.storyboard
  MC3_Team8_FOX/Source/ViewControllers/ConnectingViewController.swift
Labels: @Sherry

#66 [Feat] 코드 입력 완료시 버튼 활성화
  MC3_Team8_FOX/Resource/Storyboard/Connecting.storyboard
  MC3_Team8_FOX/Source/ViewControllers/ConnectingViewController.swift
Labels: @Aesop

#68 Connectingview -> develop으로 merge
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/Connecting.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/ViewControllers/ConnectingViewController.swift
Labels: @Eddy

#70 newMeetScheduleView -> develop으로 merge
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/Connecting.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Resource/Storyboard/WriteRequest.storyboard
  MC3_Team8_FOX/Source/Component/CheckBoxDelegate.swift
  MC3_Team8_FOX/Source/Component/CheckBoxView.swift
  MC3_Team8_FOX/Source/Component/CheckBoxView.xib
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/Supports/UIColor+Extension.swift
  MC3_Team8_FOX/Source/Supports/UIView+Extension.swift
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestTableViewCell.swift
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/ConnectingViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleTableViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController2.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/ScheduleCell.swift
  MC3_Team8_FOX/Source/ViewControllers/SendingNoticeCell.swift
  MC3_Team8_FOX/Source/ViewControllers/TextFieldOfTableViewCell.swift
Labels: @Eddy

#71 recentRequestView -> develop으로 merge
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Resource/Storyboard/RecentRequest.storyboard
  MC3_Team8_FOX/Source/Data/AppointmentMockData.json
  MC3_Team8_FOX/Source/Data/Model.swift
  MC3_Team8_FOX/Source/Data/recentRequestArray.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/ReceivedRequestCell.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
Labels: @Eddy

#72 rejectReasonView -> develop으로 merge
  MC3_Team8_FOX/Resource/Storyboard/RejectReason.storyboard
  MC3_Team8_FOX/Source/ViewControllers/RejectReasonViewController.swift
Labels: @Eddy

#73 acceptRequestView -> develop으로 merge
  MC3_Team8_FOX/Assets.xcassets/BaseGray.colorset/Contents.json
Labels: @Eddy
