Repository DeveloperAcademy-POSTECH/MC3-Team8-FOX, pull requests merged in 2022-07, with the labels that each got.

#27 Docs📚: Skills 형식 수정
  README.md
Labels: @Eddy

#28 Feat✨: mock data 추가
  .github/ISSUE_TEMPLATE/-bug-----.md
  .github/ISSUE_TEMPLATE/-feat-----.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/Base.lproj/LaunchScreen.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Source/Data/AppointmentMockData.json
  MC3_Team8_FOX/Source/Data/LoadData.swift
  MC3_Team8_FOX/Source/Data/Model.swift
  MC3_Team8_FOX/Source/Data/UserMockData.json
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/ScheduleCell.swift
Labels: @Keily

#40 meetScheduleView에서의 상단탭을 이용한 뷰 전환
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Resource/Storyboard/RecentRequest.storyboard
  MC3_Team8_FOX/Source/Data/Model.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
Labels: @Eddy

#44 [Feat] MeetScheduleView와 Connecting View 연결하기
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/Connecting.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
Labels: @Sherry

#45 AcceptRequestView 전달사항 체크박스, JSON데이터 업로드 연결
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/CompleteRequest.storyboard
  MC3_Team8_FOX/Source/Component/CheckBoxDelegate.swift
  MC3_Team8_FOX/Source/Component/CheckBoxView.swift
  MC3_Team8_FOX/Source/Component/CheckBoxView.xib
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/SendingNoticeCell.swift
Labels: @Eddy

#43 Meet schedule view
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Resource/Storyboard/RecentRequest.storyboard
  MC3_Team8_FOX/Source/Data/Model.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
Labels: @Eddy

#42 Feat✨: Write Request View
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Resource/Storyboard/WriteRequest.storyboard
  MC3_Team8_FOX/Source/ViewControllers/WriteRequestViewController.swift
Labels: @Aesop

#46 Accept request view
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/CompleteRequest.storyboard
  MC3_Team8_FOX/Source/Component/CheckBoxDelegate.swift
  MC3_Team8_FOX/Source/Component/CheckBoxView.swift
  MC3_Team8_FOX/Source/Component/CheckBoxView.xib
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/SendingNoticeCell.swift
Labels: @Eddy

#51 [Feat] Write request view 데이터 입력받은 데이터를 요청함에서 보여주기
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Info.plist
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/RecentRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/WriteRequest.storyboard
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/WriteRequestViewController.swift
Labels: @Aesop

#55 Write request view +버튼 클릭 시 Textfield 추가 & 전달사항 저장 추가
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX.xcodeproj/xcshareddata/xcschemes/MC3_Team8_FOX.xcscheme
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Resource/Storyboard/RecentRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/WriteRequest.storyboard
  MC3_Team8_FOX/Source/Data/LoadData.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/TextFieldOfTableViewCell.swift
  MC3_Team8_FOX/Source/ViewControllers/WriteRequestViewController.swift
Labels: @Eddy

#58 Feat✨: Accept request view
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Assets.xcassets/Navy.colorset/Contents.json
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/CompleteRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/RejectReason.storyboard
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
Labels: @Aesop, @Livvy

#64 AcceptRequest에서 작성한 데이터, MeetSchedule 셀로 데이터 전달
  MC3_Team8_FOX.xcodeproj/project.pbxproj
  MC3_Team8_FOX/Resource/Storyboard/AcceptRequest.storyboard
  MC3_Team8_FOX/Resource/Storyboard/MeetScheduleView.storyboard
  MC3_Team8_FOX/Source/Supports/AppDelegate.swift
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestTableViewCell.swift
  MC3_Team8_FOX/Source/ViewControllers/AcceptRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleTableViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/MeetScheduleViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/RecentRequestViewController.swift
  MC3_Team8_FOX/Source/ViewControllers/TextFieldOfTableViewCell.swift
Labels: @Eddy
